# Generated by Django 4.1 on 2022-08-31 16:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0002_choice_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='pic',
        ),
        migrations.AddField(
            model_name='choice',
            name='choicer',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
