# Generated by Django 4.1 on 2022-08-31 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_remove_choice_pic_choice_choicer'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='pic',
            field=models.ImageField(default='', upload_to='media/'),
        ),
    ]
