# Generated by Django 4.1 on 2022-09-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_choice_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='com',
            field=models.TextField(default=''),
        ),
    ]
